version: '3.8'
services:
  zydhan-web:
    container_name: zydhan-web
    image: node:lts-alpine
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app:rw
    expose: [8000]
    env_file: [docker.env]
    command: /bin/sh -c "npm run dev"
    networks: [nginx-proxy-network]
    restart: always

networks:
  nginx-proxy-network:
    external: true
